data = [
    {'name': 'Lionel Messi', 'follower_count': 497, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Rihanna', 'follower_count': 152, 'description': 'Musician', 'country': 'Barbados'},
    {'name': 'Neymar', 'follower_count': 218, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Justin Bieber', 'follower_count': 292, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Drake', 'follower_count': 144, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Shakira', 'follower_count': 90.4, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'UEFA Champions League', 'follower_count': 112, 'description': 'Club football competition', 'country': 'Europe'},
    {'name': 'Kylian Mbappé', 'follower_count': 111, 'description': 'Footballer', 'country': 'France'},
    {'name': 'Virat Kohli', 'follower_count': 265, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Priyanka Chopra', 'follower_count': 90.2, 'description': 'Actress', 'country': 'India'},
    {'name': 'Shraddha Kapoor', 'follower_count': 85.6, 'description': 'Actress', 'country': 'India'},
    {'name': 'Narendra Modi', 'follower_count': 83.8, 'description': 'Prime Minister of India', 'country': 'India'},
    {'name': 'Gal Gadot', 'follower_count': 109, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 617, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Jennie', 'follower_count': 82.8, 'description': 'Musician', 'country': 'South Korea'},
    {'name': 'Real Madrid CF', 'follower_count': 150, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'FC Barcelona', 'follower_count': 125, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Lisa', 'follower_count': 100, 'description': 'Musician', 'country': 'Thailand'},
    {'name': 'Nicki Minaj', 'follower_count': 229, 'description': 'Musician', 'country': 'Trinidad and Tobago'},
    {'name': 'David Beckham', 'follower_count': 86.4, 'description': 'Former footballer', 'country': 'United Kingdom'},
    {'name': 'Dua Lipa', 'follower_count': 88.5, 'description': 'Musician', 'country': 'United Kingdom'},
    {'name': 'Alia Bhatt', 'follower_count': 82.2, 'description': 'Actress', 'country': 'United Kingdom / India'},
    {'name': 'Instagram', 'follower_count': 666, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower_count': 429, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 399, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 395, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 380, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 364, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 319, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 311, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 306, 'description': 'Sportswear multinational', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 294, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 283, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 279, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 253, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 224, 'description': 'Media personality', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 216, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 206, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 184, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 179, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Cardi B', 'follower_count': 169, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Demi Lovato', 'follower_count': 157, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Chris Brown', 'follower_count': 145, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 139, 'description': 'Comedian and television host', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 110, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Vin Diesel', 'follower_count': 102, 'description': 'Actor', 'country': 'United States'},
    {'name': 'NASA', 'follower_count': 96.9, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Snoop Dogg', 'follower_count': 84.2, 'description': 'Musician', 'country': 'United States'},
    {'name': 'NBA', 'follower_count': 85.1, 'description': 'Professional basketball league', 'country': 'United States'},

]

